---
- hosts: all
  become: yes
  tasks:
  - name: installing apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
  - name: starting service
    service:
      name: apache2
      state: started
      enabled: yes