---
- hosts: all
  become: yes
  tasks:
  - name: Installing Git
    apt:
      name: git
      update_cache: yes
      state: present

# Installing GIt in ubuntu
# sudo apt-get update
# sudo apt-get install git