---
- hosts: webserver
  become: yes
  tasks:
   - name: this Insatallation only for redhat it will fail in other platforms
     fail:
       msg: "Installation is not supported for this paltform"
     when: