---
- hosts: all
  become: yes
  tasks:
  - name: installing tomcat7
    yum:
      name: tomcat7
      update_cache: yes
      state: present
  - name: starting service
    service:
      name: tomcat7
      state: started
      enabled: yes